name: Publish

on:
  push:
    branches: ["main"]
  workflow_dispatch: # Manual run

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x gradlew
        working-directory: java
      - run: ./gradlew build
        working-directory: java
      - run: npm ci
      - run: npm run build
      - run: npx wrangler pages deploy ./dist --project-name=legacymcsrc
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}